# Generated by Django 5.0 on 2023-12-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='province',
        ),
    ]
